version: "3.5"

services:
  postgres:
    image: library/postgres:10.7
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - test

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    depends_on:
      - postgres
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
      - ${KEYCLOAK_PORT:-8443}:8443
    networks:
      - test
  api:
    image: api
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - gerdau
    volumes:
      - ./api:/app
    environment:
      KEYCLOAK_URI: http://keycloak:8080/auth/
      REALM: ${REALM}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      OPENID_URL: http://keycloak:8080/auth/realms/gerdau/protocol/openid-connect
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      

volumes:
  postgres_data:

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.5.0.0/16
    name: test_net